### ISSUE TITLE
Lỗi json_encode xa_phuong

### ISSUE THREAD

**Issue by vanthao03596** [madnh/hanhchinhvn#3]
Hiện tại export đang bị lỗi trống file xa_phuong.json do "Phường Hàm Rồng" ở file "Danh sách quận huyện phường xã thuộc Tỉnh Lào Cai"

**Comment by madnh** [comment]
@vanthao03596 Thanks bạn, mình sẽ check sớm!

**Comment by madnh** [comment]
Mình đã merge PR #4 , cái này fix issue này rồi nhé @vanthao03596 !
