### ISSUE TITLE
Thị Xã Sa Pa đang trống xã/phường

### ISSUE THREAD

**Issue by viet-dinh** [madnh/hanhchinhvn#5]
File xa-phuong/088.json

Tôi thấy trong file excel có các xã như hình:
![image](https://user-images.githubusercontent.com/40446678/130629540-85812d8f-1539-4789-8b73-e103e7063e0f.png)

**Comment by madnh** [comment]
@viet-dinh Thanks bạn, mình sẽ check sớm!

**Comment by madnh** [comment]
Hi @viet-dinh,
mình đã update data mới nhất ngày 5/5/2022 và update code rồi, thanks bạn nhé!
