### ISSUE TITLE
xa-phuong/088.json lỗi 

### ISSUE THREAD

**Issue by tabvn** [madnh/hanhchinhvn#6]
file json xa-phuong/088.json bị lỗi

**Comment by madnh** [comment]
Thanks bạn, mình sẽ check sớm!

**Comment by tabvn** [comment]
Với các phường xã trong json files bị trùng nhiều lắm bạn ơi.

**Comment by madnh** [comment]
Mình đã update data mới nhất vào ngày 5/5/2022 và update code, cám ơn các bạn nhé!
